# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
