# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0003_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('data', models.BinaryField()),
            ],
        ),
    ]
