# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0005_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='bff_post_object',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='bff_req_object',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='comment_object',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='follow_object',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='vote_object',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
