# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0007_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='from_user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='bff_post_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.PhotoItem'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='bff_req_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.Bff'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='comment_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.Comment'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_readed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date readed'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='follow_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.Follow'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='vote_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.Vote'),
        ),
    ]
