# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0008_auto_20160425_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='bff_post_object',
            new_name='post_object',
        ),
    ]
