# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0009_auto_20160425_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcm_reg_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
