# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
