# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0012_user_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coupon_photo', models.ImageField(upload_to=b'')),
                ('coupon_code', models.CharField(max_length=16)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemuzeapp.Brand')),
            ],
        ),
    ]
