# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0013_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
