# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-21 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0014_auto_20170520_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 23, 36, 4, 781739, tzinfo=utc), verbose_name='valid till'),
            preserve_default=False,
        ),
    ]
