# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0015_coupon_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetensionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_delete_post', models.IntegerField()),
            ],
        ),
    ]
