# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemuzeapp', '0016_retensionpolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoitem',
            old_name='brand_assosiated',
            new_name='brand_associated',
        ),
        migrations.AddField(
            model_name='photoitem',
            name='days_to_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photoitem',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
